### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by linuxbasic** [seboschtion/inftrend-ex2#1]
- [x] Verschiedene Startpunkte (@seboschtion)
- [x] Game Over Detection (@seboschtion)
- [x] Enemies pew pew (@linuxbasic)
- [x] Smoothe Gun Amation (@linuxbasic)
- [x] Start Screen (@MurielThevenaz)
- [x] Return bei Game Over (@MurielThevenaz)
- [x] Nameninput Feld skalieren (@seboschtion)
- [ ] Score Management (@MurielThevenaz)
- [ ] Präsentation (@MurielThevenaz)
- [ ] Komische Verschmierung bei Nameninput (@MurielThevenaz)
- [x] Fadenkreuz bei Game Over (@seboschtion)
- [x] Scored/missed UI Text (@seboschtion)
